### PR TITLE
Project template

### PR DESCRIPTION
**Pull request by ateucher**
Adds infrastructure to start a new bcgov project (can choose package or analysis) from the RStudion Projects menu.

ezgif com-optimize

@stephhazlitt @boshek

### CODE REVIEW

**Comment by stephhazlitt** [comment]
Awesome work @ateucher!

**Comment by boshek** [comment]
Any way to bump it to the top of the list of project types? Also maybe README should default to Rmd?

**Comment by ateucher** [comment]
As far I can tell, no way to bump it up... as for the default README type - we have have .md as the default in `analysis_skeleton()`, and Rmd as default in `package_skeleton()` - I chose md since most people will be using the former I assume, but I could be convinced otherwise. Another way to approach it would be to create two templates - one for analyses, one for packages. Would only be 10 min work to do that.

**Comment by stephhazlitt** [comment]
The initial feedback from our first version of `bcgovr` was that the (then) default of having both Rmd & md files was confusing for new(er) users. A quick scan indicates that analysis repos mostly have an md format for the README and the packages or more one-off repos (like [EnvReportBC-RepoList](https://github.com/bcgov/EnvReportBC)) make use of the Rmd to generate a md using both code and text. I think the md should be the default (for analysis) as it speaks to a broader community of users. If users are advanced enough to want an Rmd then it is likely that they are comfortable adding one manually? Thoughts?

**Pull request merged**
