### PR TITLE
Add use_bcgov_pkgdown function and css

### PR DESCRIPTION
**Pull request by ateucher**

### CODE REVIEW

**Comment by stephhazlitt** [comment]
This is great, thanks for implementing so quickly! 💯

**Review by stephhazlitt — APPROVED** [review]

**Comment by boshek** [comment]
I am wondering about the workflow here @ateucher. Did you consider wrapping this with `pkgdown::build_site` (with `pkgdown` in suggests)? Whatever the case, I think we need to spell out the workflow a little more before merging. Just working through it now.

**Comment by ateucher** [comment]
Yup, agreed we need to flesh out the documentation before merging. I don't really want to add it to Suggests as I don't think it's necessary - we just want to set up the template, which doesn't require pkgdown. I was going for emulating `usethis::use_pkgdown()` which just sets up the template (and doesn't suggest pkgdown)

**Review by boshek — APPROVED** [review]

**Comment by ateucher** [comment]
Closing in favour of #50 🤦‍♂

**Pull request closed without merging**
