### PR TITLE
R setup

### PR DESCRIPTION
**Pull request by ateucher**
Add a couple of user-facing functions that help a user set up R on a government computer. Essential most of [this](https://github.com/bcgov/bcgov-data-science-resources/wiki/Installing-R-&-RStudio)  but from within R, hopefully more easily and takes care of some other things.

`set_home()` sets the users HOME environment variable to a location on the C drive which accomplishes two things - speeds up RStudio considerably, and ensures the default package library is on the `C:` drive. It also copies any existing `.Rprofile` or `.Renviron` file from their previous HOME to the new HOME.

`set_cran_repo()` adds to (or creates if necessary) the global `.Rprofile` file to set https://cran.rstudio.com as the default CRAN mirror.

I tried to make both of these ensure that the changes are enacted immediately so that a restart isn't required...

@boshek if you're willing to test these out that would be great (as you have a Windows machine).

### CODE REVIEW

**Comment by ateucher** [comment]
I also thought about wrapping these into a single function like `setup_bcgovr()` so a new user could install R and RStudio, install bcgovr, run `bcgovr::setup_bcgovr()` and be off to the races...

**Comment by boshek** [comment]
I think I see a little problem here. If users have to install `bcgovr` before setting their environmental variable, any packages needed to install `bcgovr` itself will need to be also installed (i.e. `remotes`) and then also `bcgovr` itself will be installed in the original library location (likely `H:\` in our circumstances). Then when the `HOME` directory is changed, neither `remotes` nor `bcgovr` are available. So then we'd have to transfer packages over the new HOME directory or else users will have to reinstall both `remotes` and `bcgovr`. 

I see that you've moved over the `.Renviron` and `.Rprofile` but not the package so before doing the work I want to confirm agreement that we also need to copy over the packages.

**Comment by ateucher** [comment]
Oh blah. That makes things a bit messier doesn't it... A couple of other options... just have a script at a url that people could `source()`, but from a security point of view I don't know about encouraging that kind of practice... or make a tiny package with just these functions. Thoughts?

**Comment by boshek** [comment]
Adding this here for posterity in case I need to test this again: 

First I removed bcgovr from the library located at "%USERPROFILE%":
```
remove.packages("bcgovr")

Because I already had my HOME set to `%USERPROFILE%` I had to reset it to the `%HOMEDRIVE%`:
```
setx HOME "%HOMEDRIVE%"
```
Then I opened R and tested that the HOME path was indeed ,libPaths on the shared H drive:

```
.libPaths()
```
Next I installed the remotes package then bcgovr:
```
install.packages("remotes")
remotes::install_github("bcgov/bcgovr")
```
Then I ran `set_home()`.

This took a really long time to copy and the installation of bcgovr was quite long as well.

**Pull request merged**
