### PR TITLE
New badges

### PR DESCRIPTION
**Pull request by stephhazlitt**
For review and merging @ateucher @boshek.

### CODE REVIEW

**Comment by ateucher** [comment]
Looks beautiful, nicely done! Do you also want to bump the version in DESCRIPTION (0.1.4) and add a NEWS.md item?

**Comment by stephhazlitt** [comment]
Will do, thanks for the review.

**Comment by stephhazlitt** [comment]
NEWS and DESCRIPTION now updated @ateucher.

**Comment by ateucher** [comment]
Woot! Looks great! 🎊

**Pull request merged**
