### PR TITLE
Struct options

### LINKED ISSUE #10: sub-folder structure
Add sub-folders, as per the guidelines in the recently published paper ["Good Enough Practices in Scientific Computing"](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510) -- Summary of Practices, 4b - 4e

* doc
* data
* scr (for scripts, e.g. 01_load.r that are already created via `bcgovr`)
* bin

### PR DESCRIPTION
**Pull request by ateucher**
Adds the ability to specify a different file/folder structure than the default. Closes #10

### CODE REVIEW

**Comment by ateucher** [comment]
@boshek or @stephhazlitt would either of you like to review? If not I'll just go ahead and merge...

**Comment by boshek** [comment]
Seems all good to me. The only thought I've had is to have canned values for `dir_struct` with recognizable names that specify a file structure. But I need think more and whether that actually makes this simpler or more complicated.

**Comment by ateucher** [comment]
Can you give an example of what you mean? There is a default structure: `c("R/","out/", "graphics/", "data/", "01_load.R", "02_clean.R", "03_analysis.R", "04_output.R", "internal.R", "run_all.R")`, but I guess you are talking about something different?

**Comment by ateucher** [comment]
Oh I know what you mean now! A set of pre-canned directory structures to choose from.  Not a bad idea, but I think I'll merge this and we can think more about that.

**Pull request merged**
